---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
#  hiera_data_path: hieradata
  puppet_debug: true
  puppet_verbose: true
#  require_chef_omnibus: false
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7
#  - name: centos-6
#  - name: alpine-3.7

suites:
  - name: default
    run_list:
    attributes:
