---
driver:
  name: docker
## https://github.com/test-kitchen/kitchen-docker/issues/54
  use_sudo: false

transport:
  name: sftp

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
#  hiera_data_path: hieradata
#  puppet_debug: true
  puppet_verbose: true
#  require_chef_omnibus: false
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver_config:
# https://github.com/test-kitchen/kitchen-docker/issues/285
      provision_command: mkdir -p /run/sshd
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7
#  - name: alpine-3.6

suites:
  - name: default
    run_list:
    attributes:
